"""Guards on the mutation corpus manifest (generated by scripts/plant_mutations.py)."""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
M = json.loads((REPO / "corpus" / "mutations.json").read_text())


def test_meets_scale_and_class_targets():
    # wargame Move 1.3: >=100 planted instances across >=8 attack classes
    assert M["counts"]["bad"] >= 100
    bad_classes = {i["class"] for i in M["instances"] if i["label"] == "bad"}
    assert len(bad_classes) >= 8


def test_holdout_is_class_level_not_instance_level():
    """A class lives entirely in one split — no class straddles tune/holdout."""
    split_by_class = {}
    for inst in M["instances"]:
        split_by_class.setdefault(inst["class"], set()).add(inst["split"])
    for cls, splits in split_by_class.items():
        assert len(splits) == 1, f"{cls} straddles splits {splits}"
    # and the holdout split is non-empty (recall must be scored on unseen classes)
    assert M["splits"]["holdout"] > 0


def test_manifest_counts_match_instances():
    assert M["counts"]["total"] == len(M["instances"])
    assert M["counts"]["bad"] == sum(1 for i in M["instances"] if i["label"] == "bad")
    assert M["counts"]["good"] == sum(1 for i in M["instances"] if i["label"] == "good")


def test_negatives_present_for_precision():
    # hard negatives (the real-world FP idioms) must exist so precision is measurable
    assert M["splits"]["negative"] > 0
    assert any(i["label"] == "good" for i in M["instances"])
